# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WnMain.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1901, 841))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 281, 791))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(72, 60, 131, 278))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.spinBoxVT = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxVT.setFont(font)
        self.spinBoxVT.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxVT.setMaximum(255)
        self.spinBoxVT.setProperty("value", 0)
        self.spinBoxVT.setObjectName("spinBoxVT")
        self.verticalLayout_10.addWidget(self.spinBoxVT)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.verticalLayout_13.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.spinBoxVL = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxVL.setFont(font)
        self.spinBoxVL.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxVL.setMaximum(255)
        self.spinBoxVL.setProperty("value", 0)
        self.spinBoxVL.setObjectName("spinBoxVL")
        self.verticalLayout_11.addWidget(self.spinBoxVL)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.spinBoxDF = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxDF.setFont(font)
        self.spinBoxDF.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxDF.setMinimum(1)
        self.spinBoxDF.setMaximum(500000000)
        self.spinBoxDF.setProperty("value", 1)
        self.spinBoxDF.setObjectName("spinBoxDF")
        self.verticalLayout_12.addWidget(self.spinBoxDF)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.updatebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.updatebutton.setEnabled(False)
        self.updatebutton.setObjectName("updatebutton")
        self.verticalLayout_14.addWidget(self.updatebutton)
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(300, 10, 1591, 791))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.TSMplWidget = TSMplWidget(self.frame_4)
        self.TSMplWidget.setGeometry(QtCore.QRect(0, 0, 1591, 791))
        self.TSMplWidget.setAutoFillBackground(False)
        self.TSMplWidget.setObjectName("TSMplWidget")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 281, 791))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 121, 17))
        self.label_3.setObjectName("label_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 170, 261, 266))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.MaxVLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.MaxVLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxVLabel.setObjectName("MaxVLabel")
        self.gridLayout.addWidget(self.MaxVLabel, 0, 0, 1, 1)
        self.MaxIndexLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.MaxIndexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxIndexLabel.setObjectName("MaxIndexLabel")
        self.gridLayout.addWidget(self.MaxIndexLabel, 0, 1, 1, 1)
        self.MaxVLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.MaxVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxVLineEdit.setReadOnly(True)
        self.MaxVLineEdit.setObjectName("MaxVLineEdit")
        self.gridLayout.addWidget(self.MaxVLineEdit, 1, 0, 1, 1)
        self.MaxIndexLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.MaxIndexLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxIndexLineEdit.setReadOnly(True)
        self.MaxIndexLineEdit.setObjectName("MaxIndexLineEdit")
        self.gridLayout.addWidget(self.MaxIndexLineEdit, 1, 1, 1, 1)
        self.MedianLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.MedianLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MedianLabel.setObjectName("MedianLabel")
        self.gridLayout.addWidget(self.MedianLabel, 2, 0, 1, 1)
        self.VarianceLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.VarianceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VarianceLabel.setObjectName("VarianceLabel")
        self.gridLayout.addWidget(self.VarianceLabel, 2, 1, 1, 1)
        self.MedianLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.MedianLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MedianLineEdit.setReadOnly(True)
        self.MedianLineEdit.setObjectName("MedianLineEdit")
        self.gridLayout.addWidget(self.MedianLineEdit, 3, 0, 1, 1)
        self.VarianceLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.VarianceLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.VarianceLineEdit.setReadOnly(True)
        self.VarianceLineEdit.setObjectName("VarianceLineEdit")
        self.gridLayout.addWidget(self.VarianceLineEdit, 3, 1, 1, 1)
        self.RMSLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.RMSLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RMSLabel.setObjectName("RMSLabel")
        self.gridLayout.addWidget(self.RMSLabel, 4, 0, 1, 1)
        self.StandardDevLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.StandardDevLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StandardDevLabel.setObjectName("StandardDevLabel")
        self.gridLayout.addWidget(self.StandardDevLabel, 4, 1, 1, 1)
        self.RMSLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.RMSLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.RMSLineEdit.setReadOnly(True)
        self.RMSLineEdit.setObjectName("RMSLineEdit")
        self.gridLayout.addWidget(self.RMSLineEdit, 5, 0, 1, 1)
        self.StandardDLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.StandardDLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.StandardDLineEdit.setReadOnly(True)
        self.StandardDLineEdit.setObjectName("StandardDLineEdit")
        self.gridLayout.addWidget(self.StandardDLineEdit, 5, 1, 1, 1)
        self.Median2Label = QtWidgets.QLabel(self.layoutWidget1)
        self.Median2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Median2Label.setObjectName("Median2Label")
        self.gridLayout.addWidget(self.Median2Label, 6, 0, 1, 1)
        self.MeanLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.MeanLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MeanLabel.setObjectName("MeanLabel")
        self.gridLayout.addWidget(self.MeanLabel, 6, 1, 1, 1)
        self.Median2LineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Median2LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Median2LineEdit.setReadOnly(True)
        self.Median2LineEdit.setObjectName("Median2LineEdit")
        self.gridLayout.addWidget(self.Median2LineEdit, 7, 0, 1, 1)
        self.MeanLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.MeanLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MeanLineEdit.setReadOnly(True)
        self.MeanLineEdit.setObjectName("MeanLineEdit")
        self.gridLayout.addWidget(self.MeanLineEdit, 7, 1, 1, 1)
        self.SummLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.SummLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SummLabel.setObjectName("SummLabel")
        self.gridLayout.addWidget(self.SummLabel, 8, 0, 1, 1)
        self.ModeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.ModeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModeLabel.setObjectName("ModeLabel")
        self.gridLayout.addWidget(self.ModeLabel, 8, 1, 1, 1)
        self.SummLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SummLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.SummLineEdit.setReadOnly(True)
        self.SummLineEdit.setObjectName("SummLineEdit")
        self.gridLayout.addWidget(self.SummLineEdit, 9, 0, 1, 1)
        self.ModeLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ModeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ModeLineEdit.setReadOnly(True)
        self.ModeLineEdit.setObjectName("ModeLineEdit")
        self.gridLayout.addWidget(self.ModeLineEdit, 9, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(300, 10, 1591, 791))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MplWidget = MplWidget(self.frame_5)
        self.MplWidget.setGeometry(QtCore.QRect(0, 0, 1591, 791))
        self.MplWidget.setObjectName("MplWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_7 = QtWidgets.QFrame(self.tab_2)
        self.frame_7.setGeometry(QtCore.QRect(300, 10, 1591, 791))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.SensorMplWidget = SensorMplWidget(self.frame_7)
        self.SensorMplWidget.setGeometry(QtCore.QRect(0, 0, 1591, 791))
        self.SensorMplWidget.setObjectName("SensorMplWidget")
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 281, 791))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 70, 121, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TempLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.TempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TempLabel.setObjectName("TempLabel")
        self.verticalLayout.addWidget(self.TempLabel)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget2)
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 430, 121, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PressLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.PressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PressLabel.setObjectName("PressLabel")
        self.verticalLayout_2.addWidget(self.PressLabel)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.layoutWidget3)
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_2.addWidget(self.lcdNumber_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 200, 241, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MaxVTLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.MaxVTLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxVTLabel.setObjectName("MaxVTLabel")
        self.gridLayout_2.addWidget(self.MaxVTLabel, 0, 0, 1, 1)
        self.MinValueTLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.MinValueTLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MinValueTLabel.setObjectName("MinValueTLabel")
        self.gridLayout_2.addWidget(self.MinValueTLabel, 0, 1, 1, 1)
        self.MinTVLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.MinTVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MinTVLineEdit.setReadOnly(True)
        self.MinTVLineEdit.setObjectName("MinTVLineEdit")
        self.gridLayout_2.addWidget(self.MinTVLineEdit, 1, 1, 1, 1)
        self.MaxVTLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.MaxVTLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxVTLineEdit.setReadOnly(True)
        self.MaxVTLineEdit.setObjectName("MaxVTLineEdit")
        self.gridLayout_2.addWidget(self.MaxVTLineEdit, 1, 0, 1, 1)
        self.ADFTLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.ADFTLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ADFTLabel.setObjectName("ADFTLabel")
        self.gridLayout_2.addWidget(self.ADFTLabel, 2, 0, 1, 1)
        self.MeanTLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.MeanTLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MeanTLabel.setObjectName("MeanTLabel")
        self.gridLayout_2.addWidget(self.MeanTLabel, 2, 1, 1, 1)
        self.ADFTLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ADFTLineEdit.setText("")
        self.ADFTLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ADFTLineEdit.setReadOnly(True)
        self.ADFTLineEdit.setObjectName("ADFTLineEdit")
        self.gridLayout_2.addWidget(self.ADFTLineEdit, 3, 0, 1, 1)
        self.MeanTLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.MeanTLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MeanTLineEdit.setReadOnly(True)
        self.MeanTLineEdit.setObjectName("MeanTLineEdit")
        self.gridLayout_2.addWidget(self.MeanTLineEdit, 3, 1, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 580, 241, 131))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MaxVPLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.MaxVPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxVPLabel.setObjectName("MaxVPLabel")
        self.gridLayout_3.addWidget(self.MaxVPLabel, 0, 0, 1, 1)
        self.MinValuePLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.MinValuePLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MinValuePLabel.setObjectName("MinValuePLabel")
        self.gridLayout_3.addWidget(self.MinValuePLabel, 0, 1, 1, 1)
        self.MinPVLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.MinPVLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MinPVLineEdit.setReadOnly(True)
        self.MinPVLineEdit.setObjectName("MinPVLineEdit")
        self.gridLayout_3.addWidget(self.MinPVLineEdit, 1, 1, 1, 1)
        self.MaxVPLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.MaxVPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxVPLineEdit.setReadOnly(True)
        self.MaxVPLineEdit.setObjectName("MaxVPLineEdit")
        self.gridLayout_3.addWidget(self.MaxVPLineEdit, 1, 0, 1, 1)
        self.ADFPLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.ADFPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ADFPLabel.setObjectName("ADFPLabel")
        self.gridLayout_3.addWidget(self.ADFPLabel, 2, 0, 1, 1)
        self.MeanPLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.MeanPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MeanPLabel.setObjectName("MeanPLabel")
        self.gridLayout_3.addWidget(self.MeanPLabel, 2, 1, 1, 1)
        self.ADFPLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.ADFPLineEdit.setText("")
        self.ADFPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ADFPLineEdit.setReadOnly(True)
        self.ADFPLineEdit.setObjectName("ADFPLineEdit")
        self.gridLayout_3.addWidget(self.ADFPLineEdit, 3, 0, 1, 1)
        self.MeanPLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.MeanPLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.MeanPLineEdit.setReadOnly(True)
        self.MeanPLineEdit.setObjectName("MeanPLineEdit")
        self.gridLayout_3.addWidget(self.MeanPLineEdit, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.layoutWidget7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutWidget8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutWidget9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.layoutWidget10 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget10.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget11 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget11.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(1380, 861, 531, 139))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 81, 17))
        self.label_4.setObjectName("label_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(400, 39, 121, 57))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_10.setPalette(palette)
        self.frame_10.setAutoFillBackground(True)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.daylabel = QtWidgets.QLabel(self.frame_10)
        self.daylabel.setGeometry(QtCore.QRect(20, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.daylabel.setFont(font)
        self.daylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.daylabel.setObjectName("daylabel")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setGeometry(QtCore.QRect(400, 7, 121, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 152, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 126, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 67, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 178, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 152, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 126, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 67, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 178, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 152, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 126, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 67, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 50, 82))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_11.setPalette(palette)
        self.frame_11.setAutoFillBackground(True)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.monthlabel = QtWidgets.QLabel(self.frame_11)
        self.monthlabel.setGeometry(QtCore.QRect(0, 0, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.monthlabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.monthlabel.setFont(font)
        self.monthlabel.setAutoFillBackground(False)
        self.monthlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monthlabel.setObjectName("monthlabel")
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setGeometry(QtCore.QRect(400, 100, 121, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(205, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_12.setPalette(palette)
        self.frame_12.setAutoFillBackground(True)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.yearlabel = QtWidgets.QLabel(self.frame_12)
        self.yearlabel.setGeometry(QtCore.QRect(0, 0, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.yearlabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.yearlabel.setFont(font)
        self.yearlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yearlabel.setObjectName("yearlabel")
        self.layoutWidget12 = QtWidgets.QWidget(self.frame_9)
        self.layoutWidget12.setGeometry(QtCore.QRect(30, 40, 321, 78))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.LCDUHH = QtWidgets.QLCDNumber(self.layoutWidget12)
        self.LCDUHH.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LCDUHH.setDigitCount(2)
        self.LCDUHH.setObjectName("LCDUHH")
        self.horizontalLayout_10.addWidget(self.LCDUHH)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.LCDUMM = QtWidgets.QLCDNumber(self.layoutWidget12)
        self.LCDUMM.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LCDUMM.setDigitCount(2)
        self.LCDUMM.setObjectName("LCDUMM")
        self.horizontalLayout_10.addWidget(self.LCDUMM)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.LCDUSS = QtWidgets.QLCDNumber(self.layoutWidget12)
        self.LCDUSS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LCDUSS.setDigitCount(2)
        self.LCDUSS.setObjectName("LCDUSS")
        self.horizontalLayout_10.addWidget(self.LCDUSS)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.LCDLHH = QtWidgets.QLCDNumber(self.layoutWidget12)
        self.LCDLHH.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LCDLHH.setDigitCount(2)
        self.LCDLHH.setObjectName("LCDLHH")
        self.horizontalLayout_11.addWidget(self.LCDLHH)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.LCDLMM = QtWidgets.QLCDNumber(self.layoutWidget12)
        self.LCDLMM.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LCDLMM.setDigitCount(2)
        self.LCDLMM.setObjectName("LCDLMM")
        self.horizontalLayout_11.addWidget(self.LCDLMM)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.LCDLSS = QtWidgets.QLCDNumber(self.layoutWidget12)
        self.LCDLSS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LCDLSS.setDigitCount(2)
        self.LCDLSS.setObjectName("LCDLSS")
        self.horizontalLayout_11.addWidget(self.LCDLSS)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.layoutWidget13 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget13.setGeometry(QtCore.QRect(12, 861, 1361, 141))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.layoutWidget13)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 17))
        self.label.setObjectName("label")
        self.layoutWidget14 = QtWidgets.QWidget(self.frame)
        self.layoutWidget14.setGeometry(QtCore.QRect(10, 30, 651, 101))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tcpTextEdit = QtWidgets.QTextEdit(self.layoutWidget14)
        self.tcpTextEdit.setReadOnly(True)
        self.tcpTextEdit.setObjectName("tcpTextEdit")
        self.horizontalLayout_2.addWidget(self.tcpTextEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushtcpconnect = QtWidgets.QPushButton(self.layoutWidget14)
        self.pushtcpconnect.setObjectName("pushtcpconnect")
        self.verticalLayout_3.addWidget(self.pushtcpconnect)
        self.pushtcpdisconnect = QtWidgets.QPushButton(self.layoutWidget14)
        self.pushtcpdisconnect.setEnabled(False)
        self.pushtcpdisconnect.setObjectName("pushtcpdisconnect")
        self.verticalLayout_3.addWidget(self.pushtcpdisconnect)
        self.pushtcpclear = QtWidgets.QPushButton(self.layoutWidget14)
        self.pushtcpclear.setObjectName("pushtcpclear")
        self.verticalLayout_3.addWidget(self.pushtcpclear)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget13)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 17))
        self.label_2.setObjectName("label_2")
        self.layoutWidget15 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget15.setGeometry(QtCore.QRect(10, 30, 651, 101))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serialTextEdit = QtWidgets.QTextEdit(self.layoutWidget15)
        self.serialTextEdit.setReadOnly(True)
        self.serialTextEdit.setObjectName("serialTextEdit")
        self.horizontalLayout.addWidget(self.serialTextEdit)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushstartSerial = QtWidgets.QPushButton(self.layoutWidget15)
        self.pushstartSerial.setObjectName("pushstartSerial")
        self.verticalLayout_4.addWidget(self.pushstartSerial)
        self.pushstopSerial = QtWidgets.QPushButton(self.layoutWidget15)
        self.pushstopSerial.setEnabled(False)
        self.pushstopSerial.setObjectName("pushstopSerial")
        self.verticalLayout_4.addWidget(self.pushstopSerial)
        self.pushclearserial = QtWidgets.QPushButton(self.layoutWidget15)
        self.pushclearserial.setObjectName("pushclearserial")
        self.verticalLayout_4.addWidget(self.pushclearserial)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tcpTextEdit)
        MainWindow.setTabOrder(self.tcpTextEdit, self.pushtcpconnect)
        MainWindow.setTabOrder(self.pushtcpconnect, self.pushtcpclear)
        MainWindow.setTabOrder(self.pushtcpclear, self.serialTextEdit)
        MainWindow.setTabOrder(self.serialTextEdit, self.pushstartSerial)
        MainWindow.setTabOrder(self.pushstartSerial, self.pushstopSerial)
        MainWindow.setTabOrder(self.pushstopSerial, self.pushclearserial)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LAGO"))
        self.label_11.setText(_translate("MainWindow", "Voltage Threshold"))
        self.label_12.setText(_translate("MainWindow", "Voltage Level"))
        self.label_13.setText(_translate("MainWindow", "Decimation Factor"))
        self.updatebutton.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Oscilloscope"))
        self.label_3.setText(_translate("MainWindow", "Data Information"))
        self.MaxVLabel.setText(_translate("MainWindow", "Max. Value"))
        self.MaxIndexLabel.setText(_translate("MainWindow", "Max. Index(es)"))
        self.MaxVLineEdit.setText(_translate("MainWindow", "0.0"))
        self.MaxIndexLineEdit.setText(_translate("MainWindow", "0.0"))
        self.MedianLabel.setText(_translate("MainWindow", "Median"))
        self.VarianceLabel.setText(_translate("MainWindow", "Variance"))
        self.MedianLineEdit.setText(_translate("MainWindow", "0.0"))
        self.VarianceLineEdit.setText(_translate("MainWindow", "0.0"))
        self.RMSLabel.setText(_translate("MainWindow", "RMS"))
        self.StandardDevLabel.setText(_translate("MainWindow", "Standard Deviation"))
        self.RMSLineEdit.setText(_translate("MainWindow", "0.0"))
        self.StandardDLineEdit.setText(_translate("MainWindow", "0.0"))
        self.Median2Label.setText(_translate("MainWindow", "Median 2"))
        self.MeanLabel.setText(_translate("MainWindow", "Arithmetic Mean"))
        self.Median2LineEdit.setText(_translate("MainWindow", "0.0"))
        self.MeanLineEdit.setText(_translate("MainWindow", "0.0"))
        self.SummLabel.setText(_translate("MainWindow", "Summation"))
        self.ModeLabel.setText(_translate("MainWindow", "Mode"))
        self.SummLineEdit.setText(_translate("MainWindow", "0.0"))
        self.ModeLineEdit.setText(_translate("MainWindow", "0.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Histogram"))
        self.TempLabel.setText(_translate("MainWindow", "Temperature"))
        self.PressLabel.setText(_translate("MainWindow", "Pressure"))
        self.MaxVTLabel.setText(_translate("MainWindow", "Max. Value"))
        self.MinValueTLabel.setText(_translate("MainWindow", "Min. Value"))
        self.MinTVLineEdit.setText(_translate("MainWindow", "0.0"))
        self.MaxVTLineEdit.setText(_translate("MainWindow", "0.0"))
        self.ADFTLabel.setText(_translate("MainWindow", "Trend"))
        self.MeanTLabel.setText(_translate("MainWindow", "Mean"))
        self.MeanTLineEdit.setText(_translate("MainWindow", "0.0"))
        self.MaxVPLabel.setText(_translate("MainWindow", "Max. Value"))
        self.MinValuePLabel.setText(_translate("MainWindow", "Min. Value"))
        self.MinPVLineEdit.setText(_translate("MainWindow", "0.0"))
        self.MaxVPLineEdit.setText(_translate("MainWindow", "0.0"))
        self.ADFPLabel.setText(_translate("MainWindow", "Trend"))
        self.MeanPLabel.setText(_translate("MainWindow", "Mean"))
        self.MeanPLineEdit.setText(_translate("MainWindow", "0.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sensor Log"))
        self.label_4.setText(_translate("MainWindow", "Timestamp"))
        self.daylabel.setText(_translate("MainWindow", "-"))
        self.monthlabel.setText(_translate("MainWindow", "-"))
        self.yearlabel.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "UTC Time"))
        self.label_9.setText(_translate("MainWindow", "Local Time"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.label_6.setText(_translate("MainWindow", ":"))
        self.label_7.setText(_translate("MainWindow", ":"))
        self.label_10.setText(_translate("MainWindow", ":"))
        self.label.setText(_translate("MainWindow", "TCP Connection"))
        self.pushtcpconnect.setText(_translate("MainWindow", "Connect"))
        self.pushtcpdisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushtcpclear.setText(_translate("MainWindow", "Clear"))
        self.label_2.setText(_translate("MainWindow", "Serial Log"))
        self.pushstartSerial.setText(_translate("MainWindow", "Connect"))
        self.pushstopSerial.setText(_translate("MainWindow", "Disconnect"))
        self.pushclearserial.setText(_translate("MainWindow", "Clear"))

from mplwidget import MplWidget
from sensormplwidget import SensorMplWidget
from tsmplwidget import TSMplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

