# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WnMain.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1303, 891)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1281, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 281, 651))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushHistoStart = QtWidgets.QPushButton(self.frame_6)
        self.pushHistoStart.setGeometry(QtCore.QRect(80, 600, 89, 25))
        self.pushHistoStart.setObjectName("pushHistoStart")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(300, 10, 971, 651))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MplWidget = MplWidget(self.frame_5)
        self.MplWidget.setGeometry(QtCore.QRect(0, 0, 971, 651))
        self.MplWidget.setObjectName("MplWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_7 = QtWidgets.QFrame(self.tab_2)
        self.frame_7.setGeometry(QtCore.QRect(300, 10, 971, 651))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.SensorMplWidget = SensorMplWidget(self.frame_7)
        self.SensorMplWidget.setGeometry(QtCore.QRect(0, 0, 971, 651))
        self.SensorMplWidget.setObjectName("SensorMplWidget")
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 281, 651))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushSensorStart = QtWidgets.QPushButton(self.frame_8)
        self.pushSensorStart.setGeometry(QtCore.QRect(70, 600, 89, 25))
        self.pushSensorStart.setObjectName("pushSensorStart")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 281, 651))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushTSStart = QtWidgets.QPushButton(self.frame_3)
        self.pushTSStart.setGeometry(QtCore.QRect(70, 610, 89, 25))
        self.pushTSStart.setObjectName("pushTSStart")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(300, 10, 971, 651))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.TSMplWidget = TSMplWidget(self.frame_4)
        self.TSMplWidget.setGeometry(QtCore.QRect(0, 0, 971, 651))
        self.TSMplWidget.setObjectName("TSMplWidget")
        self.tabWidget.addTab(self.tab_3, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 720, 641, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 17))
        self.label.setObjectName("label")
        self.tcpTextEdit = QtWidgets.QTextEdit(self.frame)
        self.tcpTextEdit.setGeometry(QtCore.QRect(10, 30, 521, 101))
        self.tcpTextEdit.setReadOnly(True)
        self.tcpTextEdit.setObjectName("tcpTextEdit")
        self.pushtcpconnect = QtWidgets.QPushButton(self.frame)
        self.pushtcpconnect.setGeometry(QtCore.QRect(540, 40, 89, 25))
        self.pushtcpconnect.setObjectName("pushtcpconnect")
        self.pushtcpclear = QtWidgets.QPushButton(self.frame)
        self.pushtcpclear.setGeometry(QtCore.QRect(540, 100, 89, 25))
        self.pushtcpclear.setObjectName("pushtcpclear")
        self.pushtcpdisconnect = QtWidgets.QPushButton(self.frame)
        self.pushtcpdisconnect.setEnabled(False)
        self.pushtcpdisconnect.setGeometry(QtCore.QRect(540, 70, 89, 25))
        self.pushtcpdisconnect.setObjectName("pushtcpdisconnect")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(650, 720, 641, 141))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.serialTextEdit = QtWidgets.QTextEdit(self.frame_2)
        self.serialTextEdit.setGeometry(QtCore.QRect(10, 30, 521, 101))
        self.serialTextEdit.setReadOnly(True)
        self.serialTextEdit.setObjectName("serialTextEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 17))
        self.label_2.setObjectName("label_2")
        self.pushclearserial = QtWidgets.QPushButton(self.frame_2)
        self.pushclearserial.setGeometry(QtCore.QRect(540, 100, 89, 25))
        self.pushclearserial.setObjectName("pushclearserial")
        self.pushstartSerial = QtWidgets.QPushButton(self.frame_2)
        self.pushstartSerial.setGeometry(QtCore.QRect(540, 40, 89, 25))
        self.pushstartSerial.setObjectName("pushstartSerial")
        self.pushstopSerial = QtWidgets.QPushButton(self.frame_2)
        self.pushstopSerial.setEnabled(False)
        self.pushstopSerial.setGeometry(QtCore.QRect(540, 70, 89, 25))
        self.pushstopSerial.setObjectName("pushstopSerial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tcpTextEdit)
        MainWindow.setTabOrder(self.tcpTextEdit, self.pushtcpconnect)
        MainWindow.setTabOrder(self.pushtcpconnect, self.pushtcpclear)
        MainWindow.setTabOrder(self.pushtcpclear, self.serialTextEdit)
        MainWindow.setTabOrder(self.serialTextEdit, self.pushstartSerial)
        MainWindow.setTabOrder(self.pushstartSerial, self.pushstopSerial)
        MainWindow.setTabOrder(self.pushstopSerial, self.pushclearserial)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LAGO"))
        self.pushHistoStart.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Histogram"))
        self.pushSensorStart.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sensor Log"))
        self.pushTSStart.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Timestamp"))
        self.label.setText(_translate("MainWindow", "TCP Connection"))
        self.pushtcpconnect.setText(_translate("MainWindow", "Connect"))
        self.pushtcpclear.setText(_translate("MainWindow", "Clear"))
        self.pushtcpdisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label_2.setText(_translate("MainWindow", "Serial Log"))
        self.pushclearserial.setText(_translate("MainWindow", "Clear"))
        self.pushstartSerial.setText(_translate("MainWindow", "Connect"))
        self.pushstopSerial.setText(_translate("MainWindow", "Disconnect"))

from mplwidget import MplWidget
from sensormplwidget import SensorMplWidget
from tsmplwidget import TSMplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

